<!DOCTYPE html>
<html>
<head>
  <!-- Site made with Mobirise Website Builder v4.1.4, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.1.4, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="assets/images/if-terminal-128x128.png" type="image/x-icon">
  <meta name="description" content="What is an Exception
With PHP 5 came a new object oriented way of dealing with errors.

Exception handling is used to change the normal flow of the code execution if a specified error (exceptional) condition occurs. This condition is called an exception.

This is what normally happens when an exception is triggered:

The current code state is saved
The code execution will switch to a predefined (custom) exception handler function
Depending on the situation, the handler may then resume the execution from the saved code state, terminate the script execution or continue the script from a different location in the code
We will show different error handling methods:

Basic use of Exceptions
Creating a custom exception handler
Multiple exceptions
Re-throwing an exception
Setting a top level exception handler
Note: Exceptions should only be used with error conditions, and should not be used to jump to another place in the code at a specified point.

Basic Use of Exceptions
When an exception is thrown, the code following it will not be executed, and PHP will try to find the matching "catch" block.

If an exception is not caught, a fatal error will be issued with an "Uncaught Exception" message.

Lets try to throw an exception without catching it:

<?php
//create function with an exception
function checkNum($number) {
  if($number>1) {
    throw new Exception("Value must be 1 or below");
  }
  return true;
}

//trigger exception
checkNum(2);
?>
The code above will get an error like this:

Fatal error: Uncaught exception 'Exception'
with message 'Value must be 1 or below' in C:\webfolder\test.php:6
Stack trace: #0 C:\webfolder\test.php(12):
checkNum(28) #1 {main} thrown in C:\webfolder\test.php on line 6
Try, throw and catch
To avoid the error from the example above, we need to create the proper code to handle an exception.

Proper exception code should include:

Try - A function using an exception should be in a "try" block. If the exception does not trigger, the code will continue as normal. However if the exception triggers, an exception is "thrown"
Throw - This is how you trigger an exception. Each "throw" must have at least one "catch"
Catch - A "catch" block retrieves an exception and creates an object containing the exception information
Lets try to trigger an exception with valid code:

<?php
//create function with an exception
function checkNum($number) {
  if($number>1) {
    throw new Exception("Value must be 1 or below");
  }
  return true;
}

//trigger exception in a "try" block
try {
  checkNum(2);
  //If the exception is thrown, this text will not be shown
  echo 'If you see this, the number is 1 or below';
}

//catch exception
catch(Exception $e) {
  echo 'Message: ' .$e->getMessage();
}
?>
The code above will get an error like this:

Message: Value must be 1 or below
Example explained:
The code above throws an exception and catches it:

The checkNum() function is created. It checks if a number is greater than 1. If it is, an exception is thrown
The checkNum() function is called in a "try" block
The exception within the checkNum() function is thrown
The "catch" block retrieves the exception and creates an object ($e) containing the exception information
The error message from the exception is echoed by calling $e->getMessage() from the exception object
However, one way to get around the "every throw must have a catch" rule is to set a top level exception handler to handle errors that slip through.

Creating a Custom Exception Class
To create a custom exception handler you must create a special class with functions that can be called when an exception occurs in PHP. The class must be an extension of the exception class.

The custom exception class inherits the properties from PHP's exception class and you can add custom functions to it.

Lets create an exception class:

<?php
class customException extends Exception {
  public function errorMessage() {
    //error message
    $errorMsg = 'Error on line '.$this->getLine().' in '.$this->getFile()
    .': <b>'.$this->getMessage().'</b> is not a valid E-Mail address';
    return $errorMsg;
  }
}

$email = "someone@example...com";

try {
  //check if
  if(filter_var($email, FILTER_VALIDATE_EMAIL) === FALSE) {
    //throw exception if email is not valid
    throw new customException($email);
  }
}

catch (customException $e) {
  //display custom message
  echo $e->errorMessage();
}
?>
The new class is a copy of the old exception class with an addition of the errorMessage() function. Since it is a copy of the old class, and it inherits the properties and methods from the old class, we can use the exception class methods like getLine() and getFile() and getMessage().

Example explained:
The code above throws an exception and catches it with a custom exception class:

The customException() class is created as an extension of the old exception class. This way it inherits all methods and properties from the old exception class
The errorMessage() function is created. This function returns an error message if an e-mail address is invalid
The $email variable is set to a string that is not a valid e-mail address
The "try" block is executed and an exception is thrown since the e-mail address is invalid
The "catch" block catches the exception and displays the error message
Multiple Exceptions
It is possible for a script to use multiple exceptions to check for multiple conditions.

It is possible to use several if..else blocks, a switch, or nest multiple exceptions. These exceptions can use different exception classes and return different error messages:

<?php
class customException extends Exception {
  public function errorMessage() {
    //error message
    $errorMsg = 'Error on line '.$this->getLine().' in '.$this->getFile()
    .': <b>'.$this->getMessage().'</b> is not a valid E-Mail address';
    return $errorMsg;
  }
}

$email = "someone@example.com";

try {
  //check if
  if(filter_var($email, FILTER_VALIDATE_EMAIL) === FALSE) {
    //throw exception if email is not valid
    throw new customException($email);
  }
  //check for "example" in mail address
  if(strpos($email, "example") !== FALSE) {
    throw new Exception("$email is an example e-mail");
  }
}

catch (customException $e) {
  echo $e->errorMessage();
}

catch(Exception $e) {
  echo $e->getMessage();
}
?>
Example explained:
The code above tests two conditions and throws an exception if any of the conditions are not met:

The customException() class is created as an extension of the old exception class. This way it inherits all methods and properties from the old exception class
The errorMessage() function is created. This function returns an error message if an e-mail address is invalid
The $email variable is set to a string that is a valid e-mail address, but contains the string "example"
The "try" block is executed and an exception is not thrown on the first condition
The second condition triggers an exception since the e-mail contains the string "example"
The "catch" block catches the exception and displays the correct error message
If the exception thrown were of the class customException and there were no customException catch, only the base exception catch, the exception would be handled there.

Re-throwing Exceptions
Sometimes, when an exception is thrown, you may wish to handle it differently than the standard way. It is possible to throw an exception a second time within a "catch" block.

A script should hide system errors from users. System errors may be important for the coder, but are of no interest to the user. To make things easier for the user you can re-throw the exception with a user friendly message:

<?php
class customException extends Exception {
  public function errorMessage() {
    //error message
    $errorMsg = $this->getMessage().' is not a valid E-Mail address.';
    return $errorMsg;
  }
}

$email = "someone@example.com";

try {
  try {
    //check for "example" in mail address
    if(strpos($email, "example") !== FALSE) {
      //throw exception if email is not valid
      throw new Exception($email);
    }
  }
  catch(Exception $e) {
    //re-throw exception
    throw new customException($email);
  }
}

catch (customException $e) {
  //display custom message
  echo $e->errorMessage();
}
?>
Example explained:
The code above tests if the email-address contains the string "example" in it, if it does, the exception is re-thrown:

The customException() class is created as an extension of the old exception class. This way it inherits all methods and properties from the old exception class
The errorMessage() function is created. This function returns an error message if an e-mail address is invalid
The $email variable is set to a string that is a valid e-mail address, but contains the string "example"
The "try" block contains another "try" block to make it possible to re-throw the exception
The exception is triggered since the e-mail contains the string "example"
The "catch" block catches the exception and re-throws a "customException"
The "customException" is caught and displays an error message
If the exception is not caught in its current "try" block, it will search for a catch block on "higher levels".

Set a Top Level Exception Handler
The set_exception_handler() function sets a user-defined function to handle all uncaught exceptions.

<?php
function myException($exception) {
  echo "<b>Exception:</b> " . $exception->getMessage();
}

set_exception_handler('myException');

throw new Exception('Uncaught Exception occurred');
?>
The output of the code above should be something like this:

Exception: Uncaught Exception occurred
In the code above there was no "catch" block. Instead, the top level exception handler triggered. This function should be used to catch uncaught exceptions.

Rules for exceptions
Code may be surrounded in a try block, to help catch potential exceptions
Each try block or "throw" must have at least one corresponding catch block
Multiple catch blocks can be used to catch different classes of exceptions
Exceptions can be thrown (or re-thrown) in a catch block within a try block
A simple rule: If you throw something, you have to catch it.">
  <title>Php Exception Handling</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&subset=latin">
  <link rel="stylesheet" href="assets/bootstrap-material-design-font/css/material.css">
  <link rel="stylesheet" href="assets/tether/tether.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/dropdown/css/style.css">
  <link rel="stylesheet" href="assets/animate.css/animate.min.css">
  <link rel="stylesheet" href="assets/theme/css/style.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,300,700" rel="stylesheet">
  <link href="assets/fonts/style.css" rel="stylesheet">
  <link rel="stylesheet" href="assets/mobirise/css/mbr-additional.css" type="text/css">
  
  
  
</head>
<body>

<!-- Google Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-104305149-1', 'auto');
  ga('send', 'pageview');

</script>
<!-- /Google Analytics -->


<section id="ext_menu-62" data-rv-view="768">

    <nav class="navbar navbar-dropdown navbar-fixed-top">
        <div class="container">

            <div class="mbr-table">
                <div class="mbr-table-cell">

                    <div class="navbar-brand">
                        <a href="index.html" class="navbar-logo"><img src="assets/images/if-terminal-128x128.png" alt="Mobirise"></a>
                        <a class="navbar-caption" href="index.html">Tuts Point</a>
                    </div>

                </div>
                <div class="mbr-table-cell">

                    <button class="navbar-toggler pull-xs-right hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                        <div class="hamburger-icon"></div>
                    </button>

                    <ul class="nav-dropdown collapse pull-xs-right nav navbar-nav navbar-toggleable-sm" id="exCollapsingNavbar"><li class="nav-item dropdown"><a class="nav-link link" href="index.html" aria-expanded="false">HOME</a></li><li class="nav-item"><a class="nav-link link" href="PHP.html" aria-expanded="false">PHP</a></li><li class="nav-item"><a class="nav-link link" href="PRIVACY.html">PRIVACY</a></li><li class="nav-item nav-btn"><a class="nav-link btn btn-primary" href="index.html#form2-6">SUBSCRIBE</a></li></ul>
                    <button hidden="" class="navbar-toggler navbar-close" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                        <div class="close-icon"></div>
                    </button>

                </div>
            </div>

        </div>
    </nav>

</section>

<section class="engine"><a href="https://mobirise.co/d">website software</a></section><section class="mbr-section article mbr-after-navbar" id="msg-box8-6t" data-rv-view="770" style="background-color: rgb(124, 112, 107); padding-top: 160px; padding-bottom: 80px;">

    
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-xs-center">
                <h3 class="mbr-section-title display-2">Php Exception Handling</h3>
                
                
            </div>
        </div>
    </div>

</section>

<section class="mbr-section mbr-section--relative mbr-section--fixed-size" id="htmlblock-block-6u" data-rv-view="773" style="background-color: rgb(255, 255, 255);">
	<style>.block {padding-bottom:0px; padding-top:0px;}</style>		
            

    <div class="mbr-section__container mbr-section__container--isolated container">
        <div class="row block">
            <div class="mbr-box mbr-box--fixed mbr-box--adapted">
                <div class="mbr-box__magnet mbr-box__magnet--top-left mbr-section__left col-sm-8">
                    <div class="mbr-section__container mbr-section__container--middle">
                        <div class="mbr-header mbr-header--auto-align mbr-header--wysiwyg">
                            <div class="mbr-header__text tiny"></div>
                        </div>
                    </div>
                    <div class="mbr-section__container">
                        <div class="mbr-article mbr-article--auto-align mbr-article--wysiwyg"><div class="tiny"><h2>What is an Exception</h2><p>With PHP 5 came a new object oriented way of dealing with errors.</p><p>Exception handling is used to change the normal flow of the code execution if a specified error (exceptional) condition occurs. This condition is called an exception.<br><br>This is what normally happens when an exception is triggered:</p><ul><li>The current code state is saved</li><li>The code execution will switch to a predefined (custom) exception handler function</li><li>Depending on the situation, the handler may then resume the execution from the saved code state, terminate the script execution or continue the script from a different location in the code</li></ul><p>We will show different error handling methods:</p><ul><li>Basic use of Exceptions</li><li>Creating a custom exception handler</li><li>Multiple exceptions</li><li>Re-throwing an exception</li><li>Setting a top level exception handler</li></ul><p><strong>Note:</strong>&nbsp;Exceptions should only be used with error conditions, and should not be used to jump to another place in the code at a specified point.</p><h2>Basic Use of Exceptions</h2><p>When an exception is thrown, the code following it will not be executed, and PHP will try to find the matching "catch" block.</p><p>If an exception is not caught, a fatal error will be issued with an "Uncaught Exception" message.</p><p>Lets try to throw an exception without catching it:</p><div class="w3-code w3-border notranslate"><div><strong>&lt;?php</strong><br><strong>//create function with an exception</strong><br><strong>function checkNum($number) {</strong><br><strong>&nbsp;&nbsp;if($number&gt;1)&nbsp;{</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;throw new Exception("Value must be 1 or below");</strong><br><strong>&nbsp;&nbsp;}</strong><br><strong>&nbsp;&nbsp;return true;</strong><br><strong>}</strong><br><br><strong>//trigger exception</strong><br><strong>checkNum(2);</strong><br><strong>?&gt;</strong></div></div><p>The code above will get an error like this:</p><div class="w3-code w3-border notranslate"><div><strong>Fatal error</strong>: Uncaught exception 'Exception'<br>with message 'Value must be 1 or below' in C:\webfolder\test.php:6<br>Stack trace: #0 C:\webfolder\test.php(12):<br>checkNum(28) #1 {main} thrown in&nbsp;<strong>C:\webfolder\test.php</strong>&nbsp;on line&nbsp;<strong>6</strong></div></div><h2>Try, throw and catch</h2><p>To avoid the error from the example above, we need to create the proper code to handle an exception.</p><p>Proper exception code should include:</p><ol><li>Try - A function using an exception should be in a "try" block. If the exception does not trigger, the code will continue as normal. However if the exception triggers, an exception is "thrown"</li><li>Throw - This is how you trigger an exception. Each "throw" must have at least one "catch"</li><li>Catch - A "catch" block retrieves an exception and creates an object containing the exception information</li></ol><p>Lets try to trigger an exception with valid code:</p><div class="w3-code w3-border notranslate"><div><strong>&lt;?php</strong><br><strong>//create function with an exception</strong><br><strong>function checkNum($number)&nbsp;{</strong><br><strong>&nbsp;&nbsp;if($number&gt;1)&nbsp;{</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;throw new Exception("Value must be 1 or below");</strong><br><strong>&nbsp;&nbsp;}</strong><br><strong>&nbsp;&nbsp;return true;</strong><br><strong>}</strong><br><br><strong>//trigger exception in a "try" block</strong><br><strong>try&nbsp;{</strong><br><strong>&nbsp;&nbsp;checkNum(2);</strong><br><strong>&nbsp;&nbsp;//If the exception is thrown, this text will not be shown</strong><br><strong>&nbsp;&nbsp;echo 'If you see this, the number is 1 or below';</strong><br><strong>}</strong><br><br><strong>//catch exception</strong><br><strong>catch(Exception $e)&nbsp;{</strong><br><strong>&nbsp;&nbsp;echo 'Message: ' .$e-&gt;getMessage();</strong><br><strong>}</strong><br><strong>?&gt;</strong></div></div><p>The code above will get an error like this:</p><div class="w3-code w3-border notranslate"><div>Message: Value must be 1 or below</div></div><h2>Example explained:</h2><p>The code above throws an exception and catches it:</p><ol><li>The checkNum() function is created. It checks if a number is greater than 1. If it is, an exception is thrown</li><li>The checkNum() function is called in a "try" block</li><li>The exception within the checkNum() function is thrown</li><li>The "catch" block retrieves the exception and creates an object ($e) containing the exception information</li><li>The error message from the exception is echoed by calling $e-&gt;getMessage() from the exception object</li></ol><p>However, one way to get around the "every throw must have a catch" rule is to set a top level exception handler to handle errors that slip through.</p><h2>Creating a Custom Exception Class</h2><p>To create a custom exception handler you must create a special class with functions that can be called when an exception occurs in PHP. The class must be an extension of the exception class.</p><p>The custom exception class inherits the properties from PHP's exception class and you can add custom functions to it.</p><p>Lets create an exception class:</p><div class="w3-code w3-border notranslate"><div><strong>&lt;?php</strong><br><strong>class customException extends Exception&nbsp;{</strong><br><strong>&nbsp;&nbsp;public function errorMessage() {</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;//error message</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;$errorMsg = 'Error on line '.$this-&gt;getLine().' in '.$this-&gt;getFile()</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;.': &lt;b&gt;'.$this-&gt;getMessage().'&lt;/b&gt; is not a valid E-Mail address';</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;return $errorMsg;</strong><br><strong>&nbsp;&nbsp;}</strong><br><strong>}</strong><br><br><strong>$email = "someone@example...com";</strong><br><br><strong>try&nbsp;{</strong><br><strong>&nbsp;&nbsp;//check if</strong><br><strong>&nbsp;&nbsp;if(filter_var($email, FILTER_VALIDATE_EMAIL) === FALSE) {</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;//throw exception if email is not valid</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;throw new customException($email);</strong><br><strong>&nbsp;&nbsp;}</strong><br><strong>}</strong><br><br><strong>catch (customException $e)&nbsp;{</strong><br><strong>&nbsp;&nbsp;//display custom message</strong><br><strong>&nbsp;&nbsp;echo $e-&gt;errorMessage();</strong><br><strong>}</strong><br><strong>?&gt;</strong></div></div><p>The new class is a copy of the old exception class with an addition of the errorMessage() function. Since it is a copy of the old class, and it inherits the properties and methods from the old class, we can use the exception class methods like getLine() and getFile() and getMessage().</p><h2>Example explained:</h2><p>The code above throws an exception and catches it with a custom exception class:</p><ol><li>The customException() class is created as an extension of the old exception class. This way it inherits all methods and properties from the old exception class</li><li>The errorMessage() function is created. This function returns an error message if an e-mail address is invalid</li><li>The $email variable is set to a string that is not a valid e-mail address</li><li>The "try" block is executed and an exception is thrown since the e-mail address is invalid</li><li>The "catch" block catches the exception and displays the error message</li></ol><h2>Multiple Exceptions</h2><p>It is possible for a script to use multiple exceptions to check for multiple conditions.</p><p>It is possible to use several if..else blocks, a switch, or nest multiple exceptions. These exceptions can use different exception classes and return different error messages:</p><div class="w3-code w3-border notranslate"><div><strong>&lt;?php</strong><br><strong>class customException extends Exception {</strong><br><strong>&nbsp; public function errorMessage() {</strong><br><strong>&nbsp;&nbsp;&nbsp; //error message</strong><br><strong>&nbsp;&nbsp;&nbsp; $errorMsg = 'Error on line '.$this-&gt;getLine().' in '.$this-&gt;getFile()</strong><br><strong>&nbsp;&nbsp;&nbsp; .': &lt;b&gt;'.$this-&gt;getMessage().'&lt;/b&gt; is not a valid E-Mail address';</strong><br><strong>&nbsp;&nbsp;&nbsp; return $errorMsg;</strong><br><strong>&nbsp; }</strong><br><strong>}</strong><br><br><strong>$email = "someone@example.com";</strong><br><br><strong>try&nbsp;{</strong><br><strong>&nbsp;&nbsp;//check if</strong><br><strong>&nbsp;&nbsp;if(filter_var($email, FILTER_VALIDATE_EMAIL) === FALSE)&nbsp;{</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;//throw exception if email is not valid</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;throw new customException($email);</strong><br><strong>&nbsp;&nbsp;}</strong><br><strong>&nbsp;&nbsp;//check for "example" in mail address</strong><br><strong>&nbsp;&nbsp;if(strpos($email, "example") !== FALSE)&nbsp;{</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;throw new Exception("$email is an example e-mail");</strong><br><strong>&nbsp;&nbsp;}</strong><br><strong>}</strong><br><br><strong>catch (customException $e)&nbsp;{</strong><br><strong>&nbsp;&nbsp;echo $e-&gt;errorMessage();</strong><br><strong>}</strong><br><br><strong>catch(Exception $e)&nbsp;{</strong><br><strong>&nbsp;&nbsp;echo $e-&gt;getMessage();</strong><br><strong>}</strong><br><strong>?&gt;</strong></div></div><h2>Example explained:</h2><p>The code above tests two conditions and throws an exception if any of the conditions are not met:</p><ol><li>The customException() class is created as an extension of the old exception class. This way it inherits all methods and properties from the old exception class</li><li>The errorMessage() function is created. This function returns an error message if an e-mail address is invalid</li><li>The $email variable is set to a string that is a valid e-mail address, but contains the string "example"</li><li>The "try" block is executed and an exception is not thrown on the first condition</li><li>The second condition triggers an exception since the e-mail contains the string "example"</li><li>The "catch" block catches the exception and displays the correct error message</li></ol><p>If the exception thrown were of the class customException and there were no customException catch, only the base exception catch, the exception would be handled there.</p><h2>Re-throwing Exceptions</h2><p>Sometimes, when an exception is thrown, you may wish to handle it differently than the standard way. It is possible to throw an exception a second time within a "catch" block.</p><p>A script should hide system errors from users. System errors may be important for the coder, but are of no interest to the user. To make things easier for the user you can re-throw the exception with a user friendly message:</p><div class="w3-code w3-border notranslate"><div><strong>&lt;?php</strong><br><strong>class customException extends Exception&nbsp;{</strong><br><strong>&nbsp;&nbsp;public function errorMessage() {</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;//error message</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;$errorMsg = $this-&gt;getMessage().' is not a valid E-Mail address.';</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;return $errorMsg;</strong><br><strong>&nbsp;&nbsp;}</strong><br><strong>}</strong><br><br><strong>$email = "someone@example.com";</strong><br><br><strong>try&nbsp;{</strong><br><strong>&nbsp;&nbsp;try {</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;//check for "example" in mail address</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;if(strpos($email, "example") !== FALSE)&nbsp;{</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//throw exception if email is not valid</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw new Exception($email);</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;}</strong><br><strong>&nbsp;&nbsp;}</strong><br><strong>&nbsp;&nbsp;catch(Exception $e)&nbsp;{</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;//re-throw exception</strong><br><strong>&nbsp;&nbsp;&nbsp;&nbsp;throw new customException($email);</strong><br><strong>&nbsp;&nbsp;}</strong><br><strong>}</strong><br><br><strong>catch (customException $e)&nbsp;{</strong><br><strong>&nbsp;&nbsp;//display custom message</strong><br><strong>&nbsp;&nbsp;echo $e-&gt;errorMessage();</strong><br><strong>}</strong><br><strong>?&gt;</strong></div></div><h2>Example explained:</h2><p>The code above tests if the email-address contains the string "example" in it, if it does, the exception is re-thrown:</p><ol><li>The customException() class is created as an extension of the old exception class. This way it inherits all methods and properties from the old exception class</li><li>The errorMessage() function is created. This function returns an error message if an e-mail address is invalid</li><li>The $email variable is set to a string that is a valid e-mail address, but contains the string "example"</li><li>The "try" block contains another "try" block to make it possible to re-throw the exception</li><li>The exception is triggered since the e-mail contains the string "example"</li><li>The "catch" block catches the exception and re-throws a "customException"</li><li>The "customException" is caught and displays an error message</li></ol><p>If the exception is not caught in its current "try" block, it will search for a catch block on "higher levels".</p><h2>Set a Top Level Exception Handler</h2><p>The set_exception_handler() function sets a user-defined function to handle all uncaught exceptions.</p><div class="w3-code w3-border notranslate"><div><strong>&lt;?php</strong><br><strong>function myException($exception) {</strong><br><strong>&nbsp; echo "&lt;b&gt;Exception:&lt;/b&gt; " . $exception-&gt;getMessage();</strong><br><strong>}</strong><br><br><strong>set_exception_handler('myException');</strong><br><br><strong>throw new Exception('Uncaught Exception occurred');</strong><br><strong>?&gt;</strong></div></div><p>The output of the code above should be something like this:</p><div class="w3-code w3-border notranslate"><div><strong>Exception:</strong>&nbsp;Uncaught Exception occurred</div></div><p>In the code above there was no "catch" block. Instead, the top level exception handler triggered. This function should be used to catch uncaught exceptions.</p><h2>Rules for exceptions</h2><ul><li>Code may be surrounded in a try block, to help catch potential exceptions</li><li>Each try block or "throw" must have at least one corresponding catch block</li><li>Multiple catch blocks can be used to catch different classes of exceptions</li><li>Exceptions can be thrown (or re-thrown) in a catch block within a try block</li></ul><p>A simple rule: If you throw something, you have to catch it.</p></div>
						</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

	
	
</section>

<section class="mbr-footer footer4 mbr-section mbr-section-md-padding" id="contacts4-63" data-rv-view="775" style="background-color: rgb(46, 46, 46); padding-top: 90px; padding-bottom: 90px;">
    
    <div class="container">
        <div class="mbr-contacts row">
            <div class="col-sm-8">
                <div class="row">
                    <div class="col-sm-6">
                        <p><strong>Address</strong><br>MUMBAI 40001<br>MH &nbsp;: INDIA<br><br><br>
<strong>Credits</strong><br><a href="https://www.w3schools.com" class="text-warning">https://www.w3schools.com</a><strong><br></strong><br><br><br></p>
                    </div>
                    <div class="col-sm-6"><p class="mbr-contacts__text"><strong>Link</strong></p><ul class="mbr-contacts__list"><li><a href="index.html">HOME</a></li><li><a href="PHP.html">PHP</a></li><li><a href="PRIVACY.html">PRIVACY</a></li><p></p></ul></div>
                </div>
            </div>
            <div class="col-sm-4" data-form-type="formoid">
                <div data-form-alert="true">
                    <div hidden="" data-form-alert-success="true">Thanks for filling out form!</div>
                </div>
                <form action="https://mobirise.com/" method="post" data-form-title="MESSAGE">
                    <input type="hidden" value="seI4GqCpKPd1PIlpCagFTTM6RyvqgqIgvMh2ZuDUgQ9NmhBKS6e92NfiAutrjzpm7scdR44WgzHO5cm8apGHNRRRlblwl8P8Zi4Suki40EfuLDg7vhHncj63eFgM9k7M" data-form-email="true">
                    <div class="form-group">
                        <label class="form-control-label" for="contacts4-63-name">Name<span class="form-asterisk">*</span></label>
                        <input type="text" class="form-control input-sm input-inverse" name="name" required="" data-form-field="Name" id="contacts4-63-name">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="contacts4-63-email">Email<span class="form-asterisk">*</span></label>
                        <input type="email" class="form-control input-sm input-inverse" name="email" required="" data-form-field="Email" id="contacts4-63-email">
                    </div>
                    
                    <div class="form-group">
                        <label class="form-control-label" for="contacts4-63-message">Message</label>
                        <textarea class="form-control input-sm input-inverse" name="message" data-form-field="Message" rows="4" id="contacts4-63-message"></textarea>
                    </div>
                    <div class="mbr-buttons mbr-buttons--right btn-inverse"><button type="submit" class="btn btn-sm btn-black">Contact us</button></div>
                </form>
            </div>
        </div>
    </div>
</section>


  <script src="assets/web/assets/jquery/jquery.min.js"></script>
  <script src="assets/tether/tether.min.js"></script>
  <script src="assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="assets/smooth-scroll/smooth-scroll.js"></script>
  <script src="assets/viewport-checker/jquery.viewportchecker.js"></script>
  <script src="assets/dropdown/js/script.min.js"></script>
  <script src="assets/touch-swipe/jquery.touch-swipe.min.js"></script>
  <script src="assets/theme/js/script.js"></script>
  <script src="assets/formoid/formoid.min.js"></script>
  
  
  <input name="animation" type="hidden">
  </body>
</html>